package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"unicode"
)

type ProtocolMeta struct {
	EKey      string `json:"ekey"`
	Message   string `json:"message"`
	EventName string `json:"event_name"`
}

func GenerateRust(cfg *Config) error {
	enumMap, err := parseEKeyEnum(filepath.Join(cfg.ProtoDir, "cmd.proto"))
	if err != nil {
		return fmt.Errorf("parse cmd.proto: %w", err)
	}

	reqMessages, err := parseMessages(filepath.Join(cfg.ProtoDir, "cmd_req.proto"))
	if err != nil {
		return fmt.Errorf("parse cmd_req.proto: %w", err)
	}

	rspMessages, err := parseMessages(filepath.Join(cfg.ProtoDir, "cmd_rsp.proto"))
	if err != nil {
		return fmt.Errorf("parse cmd_rsp.proto: %w", err)
	}

	dspMessages, err := parseMessages(filepath.Join(cfg.ProtoDir, "cmd_dsp.proto"))
	if err != nil {
		return fmt.Errorf("parse cmd_dsp.proto: %w", err)
	}

	if err := generateProtocRust(cfg); err != nil {
		return fmt.Errorf("protoc rust: %w", err)
	}

	cmdExtPath := filepath.Join(cfg.RustOutDir, "cmd_ext.rs")
	if err := writeRustCmdExt(cmdExtPath, enumMap, reqMessages, rspMessages, dspMessages); err != nil {
		return fmt.Errorf("write cmd_ext.rs: %w", err)
	}
	fmt.Printf("Generated: %s\n", cmdExtPath)

	descPath := filepath.Join(cfg.RustOutDir, "protocol.desc")
	if err := generateDescriptorSet(cfg, descPath); err != nil {
		return fmt.Errorf("write protocol.desc: %w", err)
	}
	fmt.Printf("Generated: %s\n", descPath)

	metaPath := filepath.Join(cfg.RustOutDir, "protocol_meta.json")
	if err := writeProtocolMeta(metaPath, enumMap, reqMessages, rspMessages, dspMessages); err != nil {
		return fmt.Errorf("write protocol_meta.json: %w", err)
	}
	fmt.Printf("Generated: %s\n", metaPath)

	return nil
}

func generateProtocRust(cfg *Config) error {
	protoFiles, err := filepath.Glob(filepath.Join(cfg.ProtoDir, "*.proto"))
	if err != nil {
		return fmt.Errorf("list proto files: %w", err)
	}
	protoFiles = filterProtoFiles(protoFiles, cfg.Flag)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by genpb. DO NOT EDIT.\n\n")

	for _, pf := range protoFiles {
		content, err := os.ReadFile(pf)
		if err != nil {
			return fmt.Errorf("read %s: %w", pf, err)
		}
		pattern := regexp.MustCompile(`message\s+(\w+)\s*\{`)
		matches := pattern.FindAllStringSubmatch(string(content), -1)
		_ = matches
	}

	outPath := filepath.Join(cfg.RustOutDir, "pb.rs")

	protocExe := "protoc"
	if runtime.GOOS == "windows" {
		protocExe = "protoc.exe"
	}
	protocPath := filepath.Join(filepath.Dir(cfg.ProtocPath), protocExe)
	if cfg.ProtocPath != "" {
		protocPath = cfg.ProtocPath
	}

	tmpDescPath := filepath.Join(cfg.RustOutDir, "_tmp_fds.bin")
	defer os.Remove(tmpDescPath)

	var baseNames []string
	for _, pf := range protoFiles {
		baseNames = append(baseNames, filepath.Base(pf))
	}

	args := []string{
		"--descriptor_set_out=" + tmpDescPath,
		"--include_imports",
		"-I" + cfg.ProtoDir,
	}
	args = append(args, baseNames...)

	cmd := exec.Command(protocPath, args...)
	cmd.Dir = cfg.ProtoDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	fmt.Printf("Running: %s %s\n", protocPath, strings.Join(args, " "))
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("protoc descriptor: %w", err)
	}

	fdsBytes, err := os.ReadFile(tmpDescPath)
	if err != nil {
		return fmt.Errorf("read descriptor set: %w", err)
	}

	_ = fdsBytes
	_ = outPath

	return nil
}

func generateDescriptorSet(cfg *Config, outPath string) error {
	protoFiles, err := filepath.Glob(filepath.Join(cfg.ProtoDir, "*.proto"))
	if err != nil {
		return fmt.Errorf("list proto files: %w", err)
	}
	protoFiles = filterProtoFiles(protoFiles, cfg.Flag)

	protocExe := "protoc"
	if runtime.GOOS == "windows" {
		protocExe = "protoc.exe"
	}
	protocPath := filepath.Join(filepath.Dir(cfg.ProtocPath), protocExe)
	if cfg.ProtocPath != "" {
		protocPath = cfg.ProtocPath
	}

	var baseNames []string
	for _, pf := range protoFiles {
		baseNames = append(baseNames, filepath.Base(pf))
	}

	args := []string{
		"--descriptor_set_out=" + outPath,
		"--include_imports",
		"-I" + cfg.ProtoDir,
	}
	args = append(args, baseNames...)

	cmd := exec.Command(protocPath, args...)
	cmd.Dir = cfg.ProtoDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	fmt.Printf("Running: %s %s\n", protocPath, strings.Join(args, " "))
	return cmd.Run()
}

func writeRustCmdExt(path string, enumMap map[string]EKeyInfo, reqMessages, rspMessages, dspMessages []string) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by genpb. DO NOT EDIT.\n\n")
	buf.WriteString("use prost::Message;\n\n")

	var ekeys []EKeyInfo
	for _, info := range enumMap {
		if info.Value == 0 || info.Value == 65535 {
			continue
		}
		ekeys = append(ekeys, info)
	}
	sortEKeys(ekeys)

	buf.WriteString("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n")
	buf.WriteString("#[repr(u16)]\n")
	buf.WriteString("pub enum EKey {\n")
	for _, e := range ekeys {
		buf.WriteString(fmt.Sprintf("    %s = %d,\n", toUpperCamelCase(e.Name), e.Value))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("impl EKey {\n")
	buf.WriteString("    pub fn from_u16(v: u16) -> Option<EKey> {\n")
	buf.WriteString("        match v {\n")
	for _, e := range ekeys {
		buf.WriteString(fmt.Sprintf("            %d => Some(EKey::%s),\n", e.Value, toUpperCamelCase(e.Name)))
	}
	buf.WriteString("            _ => None,\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    pub fn as_u16(self) -> u16 {\n")
	buf.WriteString("        self as u16\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("#[derive(Clone, Debug)]\n")
	buf.WriteString("pub enum ServerMessage {\n")
	for _, msg := range append(rspMessages, dspMessages...) {
		rn := toUpperCamelCase(msg)
		buf.WriteString(fmt.Sprintf("    %s(crate::pb::%s),\n", rn, rn))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("#[derive(Clone, Debug)]\n")
	buf.WriteString("pub enum ClientMessage {\n")
	for _, msg := range reqMessages {
		rn := toUpperCamelCase(msg)
		buf.WriteString(fmt.Sprintf("    %s(crate::pb::%s),\n", rn, rn))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("pub fn encode_client_message(msg: &ClientMessage) -> (EKey, Vec<u8>) {\n")
	buf.WriteString("    match msg {\n")
	for _, msg := range reqMessages {
		if ekProto := findEKeyMatch(enumMap, msg); ekProto != "" {
			rn := toUpperCamelCase(msg)
			ek := toUpperCamelCase(ekProto)
			buf.WriteString(fmt.Sprintf("        ClientMessage::%s(inner) => (EKey::%s, inner.encode_to_vec()),\n", rn, ek))
		}
	}
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("pub fn decode_server_message(key: EKey, data: &[u8]) -> Result<ServerMessage, prost::DecodeError> {\n")
	buf.WriteString("    match key {\n")
	for _, msg := range append(rspMessages, dspMessages...) {
		if ekProto := findEKeyMatch(enumMap, msg); ekProto != "" {
			rn := toUpperCamelCase(msg)
			ek := toUpperCamelCase(ekProto)
			buf.WriteString(fmt.Sprintf("        EKey::%s => Ok(ServerMessage::%s(crate::pb::%s::decode(data)?)),\n", ek, rn, rn))
		}
	}
	buf.WriteString("        _ => Err(prost::DecodeError::new(format!(\"no decoder for key {:?}\", key))),\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n")

	return os.WriteFile(path, buf.Bytes(), 0644)
}

func writeProtocolMeta(path string, enumMap map[string]EKeyInfo, reqMessages, rspMessages, dspMessages []string) error {
	meta := make(map[string]ProtocolMeta)

	allMessages := append(append(reqMessages, rspMessages...), dspMessages...)
	for _, msg := range allMessages {
		if info, ok := enumMap[msg]; ok {
			if info.Value == 0 || info.Value == 65535 {
				continue
			}
			meta[fmt.Sprintf("%d", info.Value)] = ProtocolMeta{
				EKey:      info.Name,
				Message:   msg,
				EventName: toSnakeCase(msg),
			}
		}
	}

	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

func findEKeyMatch(enumMap map[string]EKeyInfo, msgName string) string {
	if _, ok := enumMap[msgName]; ok {
		return msgName
	}
	prefixes := []string{"Req", "Rsp", "Dsp"}
	for _, prefix := range prefixes {
		if !strings.HasPrefix(msgName, prefix) {
			continue
		}
		msgSuffix := msgName[len(prefix):]
		for eName := range enumMap {
			if !strings.HasPrefix(eName, prefix) {
				continue
			}
			ekSuffix := eName[len(prefix):]
			if strings.HasSuffix(msgSuffix, ekSuffix) || strings.HasSuffix(ekSuffix, msgSuffix) {
				return eName
			}
		}
	}
	return ""
}

func toUpperCamelCase(s string) string {
	parts := splitIdentifier(s)
	var result strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		runes := []rune(strings.ToLower(p))
		runes[0] = unicode.ToUpper(runes[0])

		upper := strings.ToUpper(p)
		if upper == "ZZZ" || upper == "ID" || upper == "OK" {
			result.WriteString(strings.Title(strings.ToLower(p)))
		} else {
			result.WriteString(string(runes))
		}
	}
	return result.String()
}

func toSnakeCase(s string) string {
	parts := splitIdentifier(s)
	var result []string
	for _, p := range parts {
		if len(p) > 0 {
			result = append(result, strings.ToLower(p))
		}
	}
	return strings.Join(result, "_")
}

func splitIdentifier(s string) []string {
	var parts []string
	var current []rune
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) {
			prevIsLower := unicode.IsLower(runes[i-1])
			nextIsLower := i+1 < len(runes) && unicode.IsLower(runes[i+1])
			if prevIsLower || (i+1 < len(runes) && nextIsLower && !prevIsLower && len(current) > 0) {
				parts = append(parts, string(current))
				current = nil
			}
		}
		if r == '_' {
			if len(current) > 0 {
				parts = append(parts, string(current))
				current = nil
			}
			continue
		}
		current = append(current, r)
	}
	if len(current) > 0 {
		parts = append(parts, string(current))
	}
	return parts
}

func sortEKeys(ekeys []EKeyInfo) {
	for i := 1; i < len(ekeys); i++ {
		for j := i; j > 0 && ekeys[j].Value < ekeys[j-1].Value; j-- {
			ekeys[j], ekeys[j-1] = ekeys[j-1], ekeys[j]
		}
	}
}
