package main

// gen_rust.go – Rust / Godot code generation driven by ProtocolManifest.
//
// Outputs (all relative to --rust_out):
//   pb.rs                  – prost types (via protoc-gen-prost, unchanged)
//   typed_protocol.rs      – EKey, ServerMessage, ClientMessage, encode/decode, COMPILED_FINGERPRINTS
//   protocol_manifest.json – stable protocol index (replaces protocol_meta.json)
//   protocol.desc          – binary FileDescriptorSet (for hotfix / prost-reflect)
//
// If --godot_out is set, an additional file is written there:
//   godot_bridge_gen.rs    – GodotClass types + mapper + NetEventGd (for gdbridge)

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// GenerateRust is the entry point for Rust/Godot code generation.
func GenerateRust(cfg *Config) error {
	// 1 ── prost types → pb.rs
	if err := generateProtocRust(cfg); err != nil {
		return fmt.Errorf("protoc rust: %w", err)
	}

	// 2 ── binary descriptor → protocol.desc
	descPath := filepath.Join(cfg.RustOutDir, "protocol.desc")
	if err := generateDescriptorSet(cfg, descPath); err != nil {
		return fmt.Errorf("write protocol.desc: %w", err)
	}
	fmt.Printf("Generated: %s\n", descPath)

	// 3 ── build ProtocolManifest from descriptor
	fds, err := loadDescriptorSet(descPath)
	if err != nil {
		return fmt.Errorf("load descriptor set: %w", err)
	}
	manifest, err := buildProtocolManifest(fds, cfg.Flag)
	if err != nil {
		return fmt.Errorf("build manifest: %w", err)
	}

	// 4 ── protocol_manifest.json
	manifestPath := filepath.Join(cfg.RustOutDir, "protocol_manifest.json")
	if err := writeProtocolManifestJSON(manifestPath, manifest); err != nil {
		return fmt.Errorf("write protocol_manifest.json: %w", err)
	}
	fmt.Printf("Generated: %s\n", manifestPath)

	// 5 ── typed_protocol.rs  (replaces cmd_ext.rs)
	typedPath := filepath.Join(cfg.RustOutDir, "typed_protocol.rs")
	if err := writeTypedProtocol(typedPath, manifest); err != nil {
		return fmt.Errorf("write typed_protocol.rs: %w", err)
	}
	fmt.Printf("Generated: %s\n", typedPath)

	// 6 ── godot_bridge_gen.rs  (optional, requires --godot_out)
	if cfg.GodotOutDir != "" {
		if err := os.MkdirAll(cfg.GodotOutDir, 0755); err != nil {
			return fmt.Errorf("create godot out dir: %w", err)
		}
		godotPath := filepath.Join(cfg.GodotOutDir, "godot_bridge_gen.rs")
		if err := writeGodotBridgeGen(godotPath, manifest); err != nil {
			return fmt.Errorf("write godot_bridge_gen.rs: %w", err)
		}
		fmt.Printf("Generated: %s\n", godotPath)
	}

	return nil
}

// ─── protoc helpers (unchanged logic, just cleaned up) ────────────────────

func generateProtocRust(cfg *Config) error {
	protoFiles, err := filepath.Glob(filepath.Join(cfg.ProtoDir, "*.proto"))
	if err != nil {
		return fmt.Errorf("list proto files: %w", err)
	}
	protoFiles = filterProtoFiles(protoFiles, cfg.Flag)

	var baseNames []string
	for _, pf := range protoFiles {
		baseNames = append(baseNames, filepath.Base(pf))
	}

	protocPath := cfg.ProtocPath
	if protocPath == "" {
		protocPath = "protoc"
		if runtime.GOOS == "windows" {
			protocPath = "protoc.exe"
		}
	}

	tmpDir, err := os.MkdirTemp("", "genpb-prost-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	args := []string{
		"--prost_out=" + tmpDir,
		"-I" + cfg.ProtoDir,
	}
	if cfg.ProtocGenProst != "" {
		if _, statErr := os.Stat(cfg.ProtocGenProst); statErr == nil {
			args = append([]string{"--plugin=protoc-gen-prost=" + cfg.ProtocGenProst}, args...)
		}
	}
	args = append(args, baseNames...)

	cmd := exec.Command(protocPath, args...)
	cmd.Dir = cfg.ProtoDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	fmt.Printf("Running: %s %s\n", protocPath, strings.Join(args, " "))
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("protoc --prost_out failed: %w\n"+
			"hint: install protoc-gen-prost via `cargo install protoc-gen-prost`\n"+
			"      or place the binary in --tools_dir", err)
	}

	var rsFiles []string
	_ = filepath.Walk(tmpDir, func(path string, info os.FileInfo, _ error) error {
		if info != nil && !info.IsDir() && strings.HasSuffix(path, ".rs") {
			rsFiles = append(rsFiles, path)
		}
		return nil
	})
	sort.Strings(rsFiles)
	if len(rsFiles) == 0 {
		return fmt.Errorf("protoc-gen-prost generated no .rs files in %s", tmpDir)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by genpb (protoc-gen-prost). DO NOT EDIT.\n\n")
	seenAttrs := map[string]bool{}
	for _, f := range rsFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("read %s: %w", f, err)
		}
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) == "// @generated" {
				continue
			}
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "#![allow(") || strings.HasPrefix(trimmed, "#[allow(") {
				if seenAttrs[trimmed] {
					continue
				}
				seenAttrs[trimmed] = true
			}
			buf.WriteString(line)
			buf.WriteByte('\n')
		}
		buf.WriteByte('\n')
	}

	outPath := filepath.Join(cfg.RustOutDir, "pb.rs")
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write pb.rs: %w", err)
	}
	fmt.Printf("Generated: %s\n", outPath)
	return nil
}

func generateDescriptorSet(cfg *Config, outPath string) error {
	protoFiles, err := filepath.Glob(filepath.Join(cfg.ProtoDir, "*.proto"))
	if err != nil {
		return fmt.Errorf("list proto files: %w", err)
	}
	protoFiles = filterProtoFiles(protoFiles, cfg.Flag)

	protocExe := "protoc"
	if runtime.GOOS == "windows" {
		protocExe = "protoc.exe"
	}
	protocPath := filepath.Join(filepath.Dir(cfg.ProtocPath), protocExe)
	if cfg.ProtocPath != "" {
		protocPath = cfg.ProtocPath
	}

	var baseNames []string
	for _, pf := range protoFiles {
		baseNames = append(baseNames, filepath.Base(pf))
	}

	args := []string{
		"--descriptor_set_out=" + outPath,
		"--include_imports",
		"-I" + cfg.ProtoDir,
	}
	args = append(args, baseNames...)

	cmd := exec.Command(protocPath, args...)
	cmd.Dir = cfg.ProtoDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	fmt.Printf("Running: %s %s\n", protocPath, strings.Join(args, " "))
	return cmd.Run()
}

// ─── typed_protocol.rs writer ────────────────────────────────────────────────

func writeTypedProtocol(path string, m *ProtocolManifest) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by genpb. DO NOT EDIT.\n")
	buf.WriteString("// Run: go run . --lang rust --flag client --rust_out <path>\n\n")
	buf.WriteString("use prost::Message;\n\n")

	// ── EKey enum ──
	buf.WriteString("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n")
	buf.WriteString("#[repr(u16)]\n")
	buf.WriteString("pub enum EKey {\n")
	for _, e := range m.Messages {
		buf.WriteString(fmt.Sprintf("    %s = %d,\n", toUpperCamelCase(e.EKeyName), e.EKeyValue))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("impl EKey {\n")
	buf.WriteString("    pub fn from_u16(v: u16) -> Option<EKey> {\n")
	buf.WriteString("        match v {\n")
	for _, e := range m.Messages {
		buf.WriteString(fmt.Sprintf("            %d => Some(EKey::%s),\n", e.EKeyValue, toUpperCamelCase(e.EKeyName)))
	}
	buf.WriteString("            _ => None,\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n\n")
	buf.WriteString("    pub fn as_u16(self) -> u16 {\n")
	buf.WriteString("        self as u16\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	// ── ServerMessage enum ──
	var serverMsgs []ManifestEntry
	for _, e := range m.Messages {
		if e.Direction == "server_to_client" {
			serverMsgs = append(serverMsgs, e)
		}
	}

	buf.WriteString("#[derive(Clone, Debug)]\n")
	buf.WriteString("pub enum ServerMessage {\n")
	for _, e := range serverMsgs {
		// variant name uses toUpperCamelCase; inner type uses exact proto message name
		buf.WriteString(fmt.Sprintf("    %s(crate::pb::%s),\n",
			toUpperCamelCase(e.MessageName), e.MessageName))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("impl ServerMessage {\n")
	buf.WriteString("    pub fn event_name(&self) -> &'static str {\n")
	buf.WriteString("        match self {\n")
	for _, e := range serverMsgs {
		buf.WriteString(fmt.Sprintf("            ServerMessage::%s(_) => %q,\n",
			toUpperCamelCase(e.MessageName), e.EventName))
	}
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	// ── ClientMessage enum ──
	var clientMsgs []ManifestEntry
	for _, e := range m.Messages {
		if e.Direction == "client_to_server" {
			clientMsgs = append(clientMsgs, e)
		}
	}

	buf.WriteString("#[derive(Clone, Debug)]\n")
	buf.WriteString("pub enum ClientMessage {\n")
	for _, e := range clientMsgs {
		buf.WriteString(fmt.Sprintf("    %s(crate::pb::%s),\n",
			toUpperCamelCase(e.MessageName), e.MessageName))
	}
	buf.WriteString("}\n\n")

	// ── encode_client_message ──
	buf.WriteString("pub fn encode_client_message(msg: &ClientMessage) -> (EKey, Vec<u8>) {\n")
	buf.WriteString("    match msg {\n")
	for _, e := range clientMsgs {
		buf.WriteString(fmt.Sprintf("        ClientMessage::%s(inner) => (EKey::%s, inner.encode_to_vec()),\n",
			toUpperCamelCase(e.MessageName), toUpperCamelCase(e.EKeyName)))
	}
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	// ── decode_server_message ──
	buf.WriteString("pub fn decode_server_message(key: EKey, data: &[u8]) -> Result<ServerMessage, prost::DecodeError> {\n")
	buf.WriteString("    match key {\n")
	for _, e := range serverMsgs {
		buf.WriteString(fmt.Sprintf("        EKey::%s => Ok(ServerMessage::%s(crate::pb::%s::decode(data)?)),\n",
			toUpperCamelCase(e.EKeyName), toUpperCamelCase(e.MessageName), e.MessageName))
	}
	// client keys fall through to error
	buf.WriteString("        _ => Err(prost::DecodeError::new(format!(\"no server decoder for key {:?}\", key))),\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	// ── COMPILED_FINGERPRINTS ──
	buf.WriteString("/// Recursive FNV-1a fingerprints for server messages with hotfix_fallback=true.\n")
	buf.WriteString("/// ProtocolRegistry compares these against runtime descriptors to detect schema drift.\n")
	buf.WriteString("pub const COMPILED_FINGERPRINTS: &[(u16, u64)] = &[\n")
	for _, e := range serverMsgs {
		if e.HotfixFallback {
			buf.WriteString(fmt.Sprintf("    (%d, 0x%016x), // %s\n",
				e.EKeyValue, e.FingerprintU64, e.EventName))
		}
	}
	buf.WriteString("];\n")

	return os.WriteFile(path, buf.Bytes(), 0644)
}

// ─── godot_bridge_gen.rs writer ──────────────────────────────────────────────

func writeGodotBridgeGen(path string, m *ProtocolManifest) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by genpb. DO NOT EDIT.\n")
	buf.WriteString("// Run: go run . --lang rust --flag client --rust_out <gnet/src/gen> --godot_out <gdbridge/src/gen>\n\n")
	buf.WriteString("use godot::prelude::*;\n")
	buf.WriteString("use gnet::typed_protocol::ServerMessage;\n\n")

	// collect data types actually used by server messages
	needed := collectRequiredDataTypes(m)

	// ── Data type GodotClasses ──
	for _, dt := range needed {
		writeGodotDataClass(&buf, dt)
	}

	// ── Server message GodotClasses ──
	for _, e := range m.Messages {
		if e.Direction == "server_to_client" {
			writeGodotMsgClass(&buf, e)
		}
	}

	// ── NetEventGd (the unified event wrapper) ──
	writeNetEventGd(&buf, m)

	return os.WriteFile(path, buf.Bytes(), 0644)
}

// collectRequiredDataTypes returns DataTypeEntry items transitively used by server messages.
func collectRequiredDataTypes(m *ProtocolManifest) []DataTypeEntry {
	dataByName := make(map[string]DataTypeEntry)
	for _, dt := range m.DataTypes {
		dataByName[dt.MessageName] = dt
	}

	needed := make(map[string]bool)
	var collect func(fields []FieldSchema)
	collect = func(fields []FieldSchema) {
		for _, f := range fields {
			if strings.HasPrefix(f.TypeName, "m.") {
				msgName := strings.TrimPrefix(f.TypeName, "m.")
				if !needed[msgName] {
					needed[msgName] = true
					if dt, ok := dataByName[msgName]; ok {
						collect(dt.Fields)
					}
				}
			}
		}
	}
	for _, msg := range m.Messages {
		if msg.Direction == "server_to_client" {
			collect(msg.Fields)
		}
	}

	var result []DataTypeEntry
	for _, dt := range m.DataTypes {
		if needed[dt.MessageName] {
			result = append(result, dt)
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].MessageName < result[j].MessageName })
	return result
}

func writeGodotDataClass(buf *bytes.Buffer, dt DataTypeEntry) {
	gName := dt.MessageName + "Gd"
	writeGodotClassStruct(buf, gName, dt.Fields)
	writeGodotClassInit(buf, gName, dt.Fields)
	writeFromPb(buf, gName, dt.MessageName, dt.Fields, false)
}

func writeGodotMsgClass(buf *bytes.Buffer, e ManifestEntry) {
	gName := toUpperCamelCase(e.MessageName) + "Gd"
	writeGodotClassStruct(buf, gName, e.Fields)
	writeGodotClassInit(buf, gName, e.Fields)
	writeFromPb(buf, gName, e.MessageName, e.Fields, true)
}

func writeGodotClassStruct(buf *bytes.Buffer, gName string, fields []FieldSchema) {
	buf.WriteString(fmt.Sprintf("#[derive(GodotClass)]\n"))
	buf.WriteString(fmt.Sprintf("#[class(base=RefCounted)]\n"))
	buf.WriteString(fmt.Sprintf("pub struct %s {\n", gName))
	buf.WriteString("    base: Base<RefCounted>,\n")
	for _, f := range fields {
		fType := godotFieldType(f.TypeName, f.Repeated)
		buf.WriteString(fmt.Sprintf("    #[var] pub %s: %s,\n", f.Name, fType))
	}
	buf.WriteString("}\n\n")
}

func writeGodotClassInit(buf *bytes.Buffer, gName string, fields []FieldSchema) {
	buf.WriteString(fmt.Sprintf("#[godot_api]\nimpl IRefCounted for %s {\n", gName))
	buf.WriteString("    fn init(base: Base<RefCounted>) -> Self {\n")
	buf.WriteString("        Self {\n")
	buf.WriteString("            base,\n")
	for _, f := range fields {
		buf.WriteString(fmt.Sprintf("            %s: %s,\n", f.Name, godotFieldDefault(f.TypeName, f.Repeated)))
	}
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
}

func writeFromPb(buf *bytes.Buffer, gName string, protoName string, fields []FieldSchema, useExactProtoName bool) {
	pbRef := protoName
	if useExactProtoName {
		pbRef = protoName // use exact proto message name for pb:: reference
	}
	buf.WriteString(fmt.Sprintf("impl %s {\n", gName))
	buf.WriteString(fmt.Sprintf("    pub fn from_pb(msg: &gnet::pb::%s) -> Gd<Self> {\n", pbRef))
	// pre-compute repeated/message fields
	for _, f := range fields {
		if f.Repeated && strings.HasPrefix(f.TypeName, "m.") {
			innerName := strings.TrimPrefix(f.TypeName, "m.")
			innerGd := innerName + "Gd"
			buf.WriteString(fmt.Sprintf("        let mut _%s: Array<Gd<%s>> = Array::new();\n", f.Name, innerGd))
			buf.WriteString(fmt.Sprintf("        for item in &msg.%s { _%s.push(&%s::from_pb(item)); }\n", f.Name, f.Name, innerGd))
		}
	}
	buf.WriteString("        Gd::from_init_fn(|base| Self {\n")
	buf.WriteString("            base,\n")
	for _, f := range fields {
		init := godotFieldInit(f)
		buf.WriteString(fmt.Sprintf("            %s: %s,\n", f.Name, init))
	}
	buf.WriteString("        })\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")
}

func writeNetEventGd(buf *bytes.Buffer, m *ProtocolManifest) {
	buf.WriteString("// ── NetEventGd: unified typed event wrapper ────────────────────────────────\n\n")
	buf.WriteString("#[derive(GodotClass)]\n")
	buf.WriteString("#[class(base=RefCounted)]\n")
	buf.WriteString("pub struct NetEventGd {\n")
	buf.WriteString("    base: Base<RefCounted>,\n")
	buf.WriteString("    #[var] pub event_name: GString,\n")
	buf.WriteString("    #[var] pub key: i64,\n")
	buf.WriteString("    #[var] pub err: i64,\n")
	buf.WriteString("    data: Option<Gd<RefCounted>>,\n")
	buf.WriteString("    hotfix_fields: Dictionary,\n")
	buf.WriteString("}\n\n")

	buf.WriteString("#[godot_api]\nimpl IRefCounted for NetEventGd {\n")
	buf.WriteString("    fn init(base: Base<RefCounted>) -> Self {\n")
	buf.WriteString("        Self { base, event_name: GString::new(), key: 0, err: 0, data: None, hotfix_fields: Dictionary::new() }\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("#[godot_api]\nimpl NetEventGd {\n")
	buf.WriteString("    /// Returns the typed message object (Gd<XxxGd>) or nil for framework events.\n")
	buf.WriteString("    #[func] pub fn get_data(&self) -> Variant {\n")
	buf.WriteString("        match &self.data {\n")
	buf.WriteString("            Some(gd) => gd.clone().to_variant(),\n")
	buf.WriteString("            None => Variant::nil(),\n")
	buf.WriteString("        }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    /// Returns filled fields Dictionary for hotfix-fallback events, otherwise empty.\n")
	buf.WriteString("    #[func] pub fn get_hotfix_fields(&self) -> Dictionary {\n")
	buf.WriteString("        self.hotfix_fields.clone()\n")
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	// ── Framework event constructors ──
	buf.WriteString("pub fn make_framework_event(name: &str) -> Gd<NetEventGd> {\n")
	buf.WriteString("    Gd::from_init_fn(|base| NetEventGd {\n")
	buf.WriteString("        base, event_name: GString::from(name), key: 0, err: 0,\n")
	buf.WriteString("        data: None, hotfix_fields: Dictionary::new(),\n")
	buf.WriteString("    })\n")
	buf.WriteString("}\n\n")

	// ── server_message_to_event ──
	buf.WriteString("/// Convert a compiled ServerMessage into a Gd<NetEventGd> ready for GDScript.\n")
	buf.WriteString("pub fn server_message_to_event(key: u16, err: u16, msg: &ServerMessage) -> Gd<NetEventGd> {\n")
	buf.WriteString("    match msg {\n")
	for _, e := range m.Messages {
		if e.Direction != "server_to_client" {
			continue
		}
		gName := toUpperCamelCase(e.MessageName) + "Gd"
		variantName := toUpperCamelCase(e.MessageName)
		buf.WriteString(fmt.Sprintf("        ServerMessage::%s(inner) => {\n", variantName))
		buf.WriteString(fmt.Sprintf("            let data = %s::from_pb(inner).upcast::<RefCounted>();\n", gName))
		buf.WriteString("            Gd::from_init_fn(|base| NetEventGd {\n")
		buf.WriteString("                base,\n")
		buf.WriteString(fmt.Sprintf("                event_name: GString::from(%q),\n", e.EventName))
		buf.WriteString("                key: key as i64,\n")
		buf.WriteString("                err: err as i64,\n")
		buf.WriteString("                data: Some(data),\n")
		buf.WriteString("                hotfix_fields: Dictionary::new(),\n")
		buf.WriteString("            })\n")
		buf.WriteString("        }\n")
	}
	buf.WriteString("    }\n")
	buf.WriteString("}\n\n")

	// ── hotfix_to_event (for HotfixEvent, uses Dictionary fallback) ──
	buf.WriteString("/// Wrap a hotfix (dynamic decode fallback) event for GDScript.\n")
	buf.WriteString("pub fn hotfix_to_event(event_name: &str, key: u16, err: u16, fields: Dictionary) -> Gd<NetEventGd> {\n")
	buf.WriteString("    Gd::from_init_fn(|base| NetEventGd {\n")
	buf.WriteString("        base,\n")
	buf.WriteString("        event_name: GString::from(event_name),\n")
	buf.WriteString("        key: key as i64,\n")
	buf.WriteString("        err: err as i64,\n")
	buf.WriteString("        data: None,\n")
	buf.WriteString("        hotfix_fields: fields,\n")
	buf.WriteString("    })\n")
	buf.WriteString("}\n")
}

// ─── Godot type helpers ───────────────────────────────────────────────────────

// godotFieldType maps a FieldSchema type_name + repeated flag to a Rust/Godot type.
func godotFieldType(typeName string, repeated bool) string {
	if repeated {
		if strings.HasPrefix(typeName, "m.") {
			msgName := strings.TrimPrefix(typeName, "m.")
			return fmt.Sprintf("Array<Gd<%sGd>>", msgName)
		}
		return fmt.Sprintf("Array<%s>", godotBaseType(typeName))
	}
	if strings.HasPrefix(typeName, "m.") {
		msgName := strings.TrimPrefix(typeName, "m.")
		return fmt.Sprintf("Option<Gd<%sGd>>", msgName)
	}
	return godotBaseType(typeName)
}

func godotBaseType(typeName string) string {
	switch typeName {
	case "bool":
		return "bool"
	case "int32", "sint32", "sfixed32", "uint32", "fixed32":
		return "i32"
	case "int64", "sint64", "sfixed64", "uint64", "fixed64":
		return "i64"
	case "float":
		return "f32"
	case "double":
		return "f64"
	case "string":
		return "GString"
	case "bytes":
		return "PackedByteArray"
	default:
		if strings.HasPrefix(typeName, "e.") {
			return "i32" // proto enum stored as i32
		}
		return "i64"
	}
}

func godotFieldDefault(typeName string, repeated bool) string {
	if repeated {
		return "Array::new()"
	}
	if strings.HasPrefix(typeName, "m.") {
		return "None"
	}
	switch typeName {
	case "bool":
		return "false"
	case "float":
		return "0.0f32"
	case "double":
		return "0.0f64"
	case "string":
		return "GString::new()"
	case "bytes":
		return "PackedByteArray::new()"
	default:
		return "0"
	}
}

// godotFieldInit generates the from_pb field initialiser expression.
func godotFieldInit(f FieldSchema) string {
	name := f.Name
	if f.Repeated {
		if strings.HasPrefix(f.TypeName, "m.") {
			// already pre-computed as local variable in writeFromPb
			return "_" + name
		}
		// repeated scalar: copy into typed Array
		return fmt.Sprintf("{ let mut arr = Array::new(); for v in &msg.%s { arr.push(*v); } arr }", name)
	}
	switch f.TypeName {
	case "string":
		return fmt.Sprintf("GString::from(&msg.%s)", name)
	case "bytes":
		return fmt.Sprintf("{ let mut arr = PackedByteArray::new(); for b in &msg.%s { arr.push(*b); } arr }", name)
	default:
		if strings.HasPrefix(f.TypeName, "m.") {
			msgName := strings.TrimPrefix(f.TypeName, "m.")
			return fmt.Sprintf("msg.%s.as_ref().map(|inner| %sGd::from_pb(inner))", name, msgName)
		}
		// scalar or enum: direct copy (prost stores enums as i32)
		return fmt.Sprintf("msg.%s", name)
	}
}
