// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from cmd.proto</summary>
  public static partial class CmdReflection {

    #region Descriptor
    /// <summary>File descriptor for cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgljbWQucHJvdG8SAnBiIt4CCgRFS2V5ItUCCgFUEgsKB0ludmFsaWQQABIM",
            "CghSZXFMb2dpbhABEgwKCFJzcExvZ2luEAISEQoNUmVxQ3JlYXRlUm9sZRAD",
            "EhEKDVJzcENyZWF0ZVJvbGUQBBIQCgxSZXFMb2dpblJvbGUQBRIQCgxSc3BM",
            "b2dpblJvbGUQBhILCgdSZXFQaW5nEGQSCwoHUnNwUGluZxBlEg4KClJlcVBp",
            "bmdaWloQZhIOCgpSc3BQaW5nWlpaEGcSEQoMUmVxRW50ZXJab25lEMgBEhEK",
            "DFJzcEVudGVyWm9uZRDJARIMCgdSZXFNb3ZlEKwCEgwKB1JzcE1vdmUQrQIS",
            "DQoIRHNwTG9naW4QkE4SEwoORHNwU3J2TWFpbnRhaW4QkU4SEAoLRHNwS2lj",
            "a1JvbGUQkk4SEQoMRHNwRW50ZXJab25lEJNOEg0KB0RzcE1vdmUQ7YECEgkK",
            "A01heBD//wNCC1oJc2VydmVyL3BiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.EKey), global::Pb.EKey.Parser, null, null, new[]{ typeof(global::Pb.EKey.Types.T) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EKey : pb::IMessage<EKey>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EKey> _parser = new pb::MessageParser<EKey>(() => new EKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.CmdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EKey(EKey other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EKey Clone() {
      return new EKey(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EKey other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EKey message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum T {
        [pbr::OriginalName("Invalid")] Invalid = 0,
        /// <summary>
        /// login
        /// </summary>
        [pbr::OriginalName("ReqLogin")] ReqLogin = 1,
        [pbr::OriginalName("RspLogin")] RspLogin = 2,
        [pbr::OriginalName("ReqCreateRole")] ReqCreateRole = 3,
        [pbr::OriginalName("RspCreateRole")] RspCreateRole = 4,
        [pbr::OriginalName("ReqLoginRole")] ReqLoginRole = 5,
        /// <summary>
        /// 登录角色返回
        /// </summary>
        [pbr::OriginalName("RspLoginRole")] RspLoginRole = 6,
        /// <summary>
        /// 心跳
        /// </summary>
        [pbr::OriginalName("ReqPing")] ReqPing = 100,
        /// <summary>
        /// 心跳
        /// </summary>
        [pbr::OriginalName("RspPing")] RspPing = 101,
        /// <summary>
        /// 心跳(客户端切换后台发送该消息)
        /// </summary>
        [pbr::OriginalName("ReqPingZZZ")] ReqPingZzz = 102,
        /// <summary>
        /// 心跳(客户端切换后台发送该消息)
        /// </summary>
        [pbr::OriginalName("RspPingZZZ")] RspPingZzz = 103,
        /// <summary>
        /// 请求进入场景
        /// </summary>
        [pbr::OriginalName("ReqEnterZone")] ReqEnterZone = 200,
        /// <summary>
        /// 响应进入场景
        /// </summary>
        [pbr::OriginalName("RspEnterZone")] RspEnterZone = 201,
        /// <summary>
        /// 移动
        /// </summary>
        [pbr::OriginalName("ReqMove")] ReqMove = 300,
        /// <summary>
        /// 响应移动
        /// </summary>
        [pbr::OriginalName("RspMove")] RspMove = 301,
        /// <summary>
        /// 同步玩家登录数据
        /// </summary>
        [pbr::OriginalName("DspLogin")] DspLogin = 10000,
        /// <summary>
        /// 同步服务器维护
        /// </summary>
        [pbr::OriginalName("DspSrvMaintain")] DspSrvMaintain = 10001,
        /// <summary>
        /// 同步玩家踢下线
        /// </summary>
        [pbr::OriginalName("DspKickRole")] DspKickRole = 10002,
        /// <summary>
        /// 准备进入场景
        /// </summary>
        [pbr::OriginalName("DspEnterZone")] DspEnterZone = 10003,
        /// <summary>
        /// 同步玩家移动
        /// </summary>
        [pbr::OriginalName("DspMove")] DspMove = 33005,
        /// <summary>
        /// 0xF000 及以上为服务器保留用
        /// </summary>
        [pbr::OriginalName("Max")] Max = 65535,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
