// Code generated by pbgen. DO NOT EDIT.
// source: cmd.proto, cmd_req.proto, cmd_rsp.proto, cmd_dsp.proto

namespace Pb
{
    public partial class Cmd
    {
        /// <summary>
        /// Command keys enumeration
        /// </summary>
        public enum EKey
        {
            Login = 1,
            CreateRole = 2,
            DeleteRole = 3,
            LoginRole = 4,
            Ping = 10,
            PingXXX = 11,
            EnterScene = 20,
            TestEnter = 21,
            LoginFast = 40000,
            LoginData = 40001,
            ServerMaintain = 40002,
            KickRole = 40003,
            PreparedEnterScene = 40004,
            Test = 40005,
        }
    }
}

namespace Pb
{
    public partial class Cmd
    {
        /// <summary>
        /// Get message type from command key
        /// </summary>
        public static System.Type GetMessageType(EKey key)
        {
            switch (key)
            {
                case EKey.Login:
                    return typeof(ReqLogin);
                case EKey.CreateRole:
                    return typeof(ReqCreateRole);
                case EKey.DeleteRole:
                    return typeof(ReqDeleteRole);
                case EKey.LoginRole:
                    return typeof(ReqLoginRole);
                case EKey.Ping:
                    return typeof(ReqPing);
                case EKey.PingXXX:
                    return typeof(ReqPingXXX);
                case EKey.EnterScene:
                    return typeof(ReqEnterScene);
                case EKey.TestEnter:
                    return typeof(ReqTestEnter);
                case EKey.Login:
                    return typeof(RspLogin);
                case EKey.CreateRole:
                    return typeof(RspCreateRole);
                case EKey.DeleteRole:
                    return typeof(RspDeleteRole);
                case EKey.LoginRole:
                    return typeof(RspLoginRole);
                case EKey.Ping:
                    return typeof(RspPing);
                case EKey.PingXXX:
                    return typeof(RspPingXXX);
                case EKey.EnterScene:
                    return typeof(RspEnterScene);
                case EKey.TestEnter:
                    return typeof(RspTestEnter);
                case EKey.LoginFast:
                    return typeof(DspLoginFast);
                case EKey.LoginData:
                    return typeof(DspLoginData);
                case EKey.ServerMaintain:
                    return typeof(DspServerMaintain);
                case EKey.KickRole:
                    return typeof(DspKickRole);
                case EKey.PreparedEnterScene:
                    return typeof(DspPreparedEnterScene);
                case EKey.Test:
                    return typeof(DspTest);
                default:
                    return null;
            }
        }
    }
}

namespace Pb
{
    public static class CmdExtensions
    {
        public static Cmd.EKey GetKey(this ReqLogin msg)
        {
            return Cmd.EKey.Login;
        }

        public static Cmd.EKey GetKey(this ReqCreateRole msg)
        {
            return Cmd.EKey.CreateRole;
        }

        public static Cmd.EKey GetKey(this ReqDeleteRole msg)
        {
            return Cmd.EKey.DeleteRole;
        }

        public static Cmd.EKey GetKey(this ReqLoginRole msg)
        {
            return Cmd.EKey.LoginRole;
        }

        public static Cmd.EKey GetKey(this ReqPing msg)
        {
            return Cmd.EKey.Ping;
        }

        public static Cmd.EKey GetKey(this ReqPingXXX msg)
        {
            return Cmd.EKey.PingXXX;
        }

        public static Cmd.EKey GetKey(this ReqEnterScene msg)
        {
            return Cmd.EKey.EnterScene;
        }

        public static Cmd.EKey GetKey(this ReqTestEnter msg)
        {
            return Cmd.EKey.TestEnter;
        }

        public static Cmd.EKey GetKey(this RspLogin msg)
        {
            return Cmd.EKey.Login;
        }

        public static Cmd.EKey GetKey(this RspCreateRole msg)
        {
            return Cmd.EKey.CreateRole;
        }

        public static Cmd.EKey GetKey(this RspDeleteRole msg)
        {
            return Cmd.EKey.DeleteRole;
        }

        public static Cmd.EKey GetKey(this RspLoginRole msg)
        {
            return Cmd.EKey.LoginRole;
        }

        public static Cmd.EKey GetKey(this RspPing msg)
        {
            return Cmd.EKey.Ping;
        }

        public static Cmd.EKey GetKey(this RspPingXXX msg)
        {
            return Cmd.EKey.PingXXX;
        }

        public static Cmd.EKey GetKey(this RspEnterScene msg)
        {
            return Cmd.EKey.EnterScene;
        }

        public static Cmd.EKey GetKey(this RspTestEnter msg)
        {
            return Cmd.EKey.TestEnter;
        }

        public static Cmd.EKey GetKey(this DspLoginFast msg)
        {
            return Cmd.EKey.LoginFast;
        }

        public static Cmd.EKey GetKey(this DspLoginData msg)
        {
            return Cmd.EKey.LoginData;
        }

        public static Cmd.EKey GetKey(this DspServerMaintain msg)
        {
            return Cmd.EKey.ServerMaintain;
        }

        public static Cmd.EKey GetKey(this DspKickRole msg)
        {
            return Cmd.EKey.KickRole;
        }

        public static Cmd.EKey GetKey(this DspPreparedEnterScene msg)
        {
            return Cmd.EKey.PreparedEnterScene;
        }

        public static Cmd.EKey GetKey(this DspTest msg)
        {
            return Cmd.EKey.Test;
        }

    }
}
