// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from data.proto</summary>
  public static partial class DataReflection {

    #region Descriptor
    /// <summary>File descriptor for data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpkYXRhLnByb3RvEgJwYhoKZW51bS5wcm90byJ3Cg9Sb2xlU3VtbWFyeURh",
            "dGESCgoCaWQYASABKBISCwoDY2lkGAIgASgSEgoKAmx2GAMgASgSEgwKBG5h",
            "bWUYBCABKAkSDAoEaWNvbhgFIAEoEhIQCgh5b3VuZ190cxgGIAEoEhIRCglj",
            "cmVhdGVfdHMYByABKBIiMwoJTG9naW5EYXRhEg4KBnJlZ2FpbhgBIAEoCBIW",
            "CgR0aW1lGAIgASgLMggucGIuVGltZSJJCgZPYmplY3QSHwoHb2JqVHlwZRgB",
            "IAEoDjIOLnBiLkVPYmpUeXBlLlQSDwoHc3ViVHlwZRgCIAEoEhINCgVjb3Vu",
            "dBgDIAEoEiJqCgVBd2FyZBINCgViYXRjaBgBIAEoEhIMCgRiaW5kGAIgASgS",
            "Eg4KBndlaWdodBgDIAEoEhILCgNqb2IYBCABKBISGgoGb2JqZWN0GAUgASgL",
            "MgoucGIuT2JqZWN0EgsKA2R1ZRgGIAEoEiJWCgRJdGVtEgsKA2lkeBgBIAEo",
            "EhIKCgJpZBgCIAEoEhILCgNjaWQYAyABKBISDQoFY291bnQYBCABKBISDAoE",
            "YmluZBgFIAEoEhILCgNkdWUYBiABKBIihQEKBFRpbWUSDAoEZHNlYxgBIAEo",
            "EhIMCgR3c2VjGAIgASgSEgwKBHdkYXkYAyABKBISCwoDc2VjGAQgASgSEg0K",
            "BXlvdW5nGAUgASgSEhIKCmxvZ2luX3RpbWUYBiABKBISEAoIb3Blbl9kYXkY",
            "ByABKBISEQoJbWVyZ2VfZGF5GAggASgSIj4KBEF0dHISGwoCdHkYASABKA4y",
            "Dy5wYi5FQXR0clR5cGUuVBILCgN2YWwYAiABKBISDAoEcmF0ZRgDIAEoEiIp",
            "CgZWZWN0b3ISCQoBeBgBIAEoEhIJCgF5GAIgASgSEgkKAXoYAyABKBJCC1oJ",
            "c2VydmVyL3BiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pb.EnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.RoleSummaryData), global::Pb.RoleSummaryData.Parser, new[]{ "Id", "Cid", "Lv", "Name", "Icon", "YoungTs", "CreateTs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.LoginData), global::Pb.LoginData.Parser, new[]{ "Regain", "Time" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Object), global::Pb.Object.Parser, new[]{ "ObjType", "SubType", "Count" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Award), global::Pb.Award.Parser, new[]{ "Batch", "Bind", "Weight", "Job", "Object", "Due" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Item), global::Pb.Item.Parser, new[]{ "Idx", "Id", "Cid", "Count", "Bind", "Due" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Time), global::Pb.Time.Parser, new[]{ "Dsec", "Wsec", "Wday", "Sec", "Young", "LoginTime", "OpenDay", "MergeDay" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Attr), global::Pb.Attr.Parser, new[]{ "Ty", "Val", "Rate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Vector), global::Pb.Vector.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RoleSummaryData : pb::IMessage<RoleSummaryData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoleSummaryData> _parser = new pb::MessageParser<RoleSummaryData>(() => new RoleSummaryData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoleSummaryData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleSummaryData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleSummaryData(RoleSummaryData other) : this() {
      id_ = other.id_;
      cid_ = other.cid_;
      lv_ = other.lv_;
      name_ = other.name_;
      icon_ = other.icon_;
      youngTs_ = other.youngTs_;
      createTs_ = other.createTs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleSummaryData Clone() {
      return new RoleSummaryData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 2;
    private long cid_;
    /// <summary>
    /// 配置cid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "lv" field.</summary>
    public const int LvFieldNumber = 3;
    private long lv_;
    /// <summary>
    /// 等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Lv {
      get { return lv_; }
      set {
        lv_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    /// <summary>
    /// 角色名字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 5;
    private long icon_;
    /// <summary>
    /// 头像
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Icon {
      get { return icon_; }
      set {
        icon_ = value;
      }
    }

    /// <summary>Field number for the "young_ts" field.</summary>
    public const int YoungTsFieldNumber = 6;
    private long youngTs_;
    /// <summary>
    /// 当天累计防沉迷时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long YoungTs {
      get { return youngTs_; }
      set {
        youngTs_ = value;
      }
    }

    /// <summary>Field number for the "create_ts" field.</summary>
    public const int CreateTsFieldNumber = 7;
    private long createTs_;
    /// <summary>
    /// 创角时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreateTs {
      get { return createTs_; }
      set {
        createTs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoleSummaryData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoleSummaryData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Cid != other.Cid) return false;
      if (Lv != other.Lv) return false;
      if (Name != other.Name) return false;
      if (Icon != other.Icon) return false;
      if (YoungTs != other.YoungTs) return false;
      if (CreateTs != other.CreateTs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Cid != 0L) hash ^= Cid.GetHashCode();
      if (Lv != 0L) hash ^= Lv.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Icon != 0L) hash ^= Icon.GetHashCode();
      if (YoungTs != 0L) hash ^= YoungTs.GetHashCode();
      if (CreateTs != 0L) hash ^= CreateTs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Id);
      }
      if (Cid != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Cid);
      }
      if (Lv != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Lv);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (Icon != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(Icon);
      }
      if (YoungTs != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(YoungTs);
      }
      if (CreateTs != 0L) {
        output.WriteRawTag(56);
        output.WriteSInt64(CreateTs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Id);
      }
      if (Cid != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Cid);
      }
      if (Lv != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Lv);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (Icon != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(Icon);
      }
      if (YoungTs != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(YoungTs);
      }
      if (CreateTs != 0L) {
        output.WriteRawTag(56);
        output.WriteSInt64(CreateTs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Id);
      }
      if (Cid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Cid);
      }
      if (Lv != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Lv);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Icon);
      }
      if (YoungTs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(YoungTs);
      }
      if (CreateTs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(CreateTs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoleSummaryData other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Cid != 0L) {
        Cid = other.Cid;
      }
      if (other.Lv != 0L) {
        Lv = other.Lv;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Icon != 0L) {
        Icon = other.Icon;
      }
      if (other.YoungTs != 0L) {
        YoungTs = other.YoungTs;
      }
      if (other.CreateTs != 0L) {
        CreateTs = other.CreateTs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadSInt64();
            break;
          }
          case 16: {
            Cid = input.ReadSInt64();
            break;
          }
          case 24: {
            Lv = input.ReadSInt64();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            Icon = input.ReadSInt64();
            break;
          }
          case 48: {
            YoungTs = input.ReadSInt64();
            break;
          }
          case 56: {
            CreateTs = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadSInt64();
            break;
          }
          case 16: {
            Cid = input.ReadSInt64();
            break;
          }
          case 24: {
            Lv = input.ReadSInt64();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            Icon = input.ReadSInt64();
            break;
          }
          case 48: {
            YoungTs = input.ReadSInt64();
            break;
          }
          case 56: {
            CreateTs = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 登陆必要数据
  /// </summary>
  public sealed partial class LoginData : pb::IMessage<LoginData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginData> _parser = new pb::MessageParser<LoginData>(() => new LoginData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginData(LoginData other) : this() {
      regain_ = other.regain_;
      time_ = other.time_ != null ? other.time_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginData Clone() {
      return new LoginData(this);
    }

    /// <summary>Field number for the "regain" field.</summary>
    public const int RegainFieldNumber = 1;
    private bool regain_;
    /// <summary>
    /// true-有可以找回的资源
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Regain {
      get { return regain_; }
      set {
        regain_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private global::Pb.Time time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Time Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Regain != other.Regain) return false;
      if (!object.Equals(Time, other.Time)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Regain != false) hash ^= Regain.GetHashCode();
      if (time_ != null) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Regain != false) {
        output.WriteRawTag(8);
        output.WriteBool(Regain);
      }
      if (time_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Regain != false) {
        output.WriteRawTag(8);
        output.WriteBool(Regain);
      }
      if (time_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Regain != false) {
        size += 1 + 1;
      }
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginData other) {
      if (other == null) {
        return;
      }
      if (other.Regain != false) {
        Regain = other.Regain;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Pb.Time();
        }
        Time.MergeFrom(other.Time);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Regain = input.ReadBool();
            break;
          }
          case 18: {
            if (time_ == null) {
              Time = new global::Pb.Time();
            }
            input.ReadMessage(Time);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Regain = input.ReadBool();
            break;
          }
          case 18: {
            if (time_ == null) {
              Time = new global::Pb.Time();
            }
            input.ReadMessage(Time);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 统一对象
  /// </summary>
  public sealed partial class Object : pb::IMessage<Object>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Object> _parser = new pb::MessageParser<Object>(() => new Object());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Object> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Object() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Object(Object other) : this() {
      objType_ = other.objType_;
      subType_ = other.subType_;
      count_ = other.count_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Object Clone() {
      return new Object(this);
    }

    /// <summary>Field number for the "objType" field.</summary>
    public const int ObjTypeFieldNumber = 1;
    private global::Pb.EObjType.Types.T objType_ = global::Pb.EObjType.Types.T.None;
    /// <summary>
    /// 主类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.EObjType.Types.T ObjType {
      get { return objType_; }
      set {
        objType_ = value;
      }
    }

    /// <summary>Field number for the "subType" field.</summary>
    public const int SubTypeFieldNumber = 2;
    private long subType_;
    /// <summary>
    /// 子类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SubType {
      get { return subType_; }
      set {
        subType_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 3;
    private long count_;
    /// <summary>
    /// 数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Object);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Object other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ObjType != other.ObjType) return false;
      if (SubType != other.SubType) return false;
      if (Count != other.Count) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ObjType != global::Pb.EObjType.Types.T.None) hash ^= ObjType.GetHashCode();
      if (SubType != 0L) hash ^= SubType.GetHashCode();
      if (Count != 0L) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ObjType != global::Pb.EObjType.Types.T.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ObjType);
      }
      if (SubType != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(SubType);
      }
      if (Count != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ObjType != global::Pb.EObjType.Types.T.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ObjType);
      }
      if (SubType != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(SubType);
      }
      if (Count != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ObjType != global::Pb.EObjType.Types.T.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ObjType);
      }
      if (SubType != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(SubType);
      }
      if (Count != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Object other) {
      if (other == null) {
        return;
      }
      if (other.ObjType != global::Pb.EObjType.Types.T.None) {
        ObjType = other.ObjType;
      }
      if (other.SubType != 0L) {
        SubType = other.SubType;
      }
      if (other.Count != 0L) {
        Count = other.Count;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ObjType = (global::Pb.EObjType.Types.T) input.ReadEnum();
            break;
          }
          case 16: {
            SubType = input.ReadSInt64();
            break;
          }
          case 24: {
            Count = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ObjType = (global::Pb.EObjType.Types.T) input.ReadEnum();
            break;
          }
          case 16: {
            SubType = input.ReadSInt64();
            break;
          }
          case 24: {
            Count = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Award : pb::IMessage<Award>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Award> _parser = new pb::MessageParser<Award>(() => new Award());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Award> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Award() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Award(Award other) : this() {
      batch_ = other.batch_;
      bind_ = other.bind_;
      weight_ = other.weight_;
      job_ = other.job_;
      object_ = other.object_ != null ? other.object_.Clone() : null;
      due_ = other.due_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Award Clone() {
      return new Award(this);
    }

    /// <summary>Field number for the "batch" field.</summary>
    public const int BatchFieldNumber = 1;
    private long batch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Batch {
      get { return batch_; }
      set {
        batch_ = value;
      }
    }

    /// <summary>Field number for the "bind" field.</summary>
    public const int BindFieldNumber = 2;
    private long bind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Bind {
      get { return bind_; }
      set {
        bind_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 3;
    private long weight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "job" field.</summary>
    public const int JobFieldNumber = 4;
    private long job_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Job {
      get { return job_; }
      set {
        job_ = value;
      }
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 5;
    private global::Pb.Object object_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Object Object {
      get { return object_; }
      set {
        object_ = value;
      }
    }

    /// <summary>Field number for the "due" field.</summary>
    public const int DueFieldNumber = 6;
    private long due_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Due {
      get { return due_; }
      set {
        due_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Award);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Award other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Batch != other.Batch) return false;
      if (Bind != other.Bind) return false;
      if (Weight != other.Weight) return false;
      if (Job != other.Job) return false;
      if (!object.Equals(Object, other.Object)) return false;
      if (Due != other.Due) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Batch != 0L) hash ^= Batch.GetHashCode();
      if (Bind != 0L) hash ^= Bind.GetHashCode();
      if (Weight != 0L) hash ^= Weight.GetHashCode();
      if (Job != 0L) hash ^= Job.GetHashCode();
      if (object_ != null) hash ^= Object.GetHashCode();
      if (Due != 0L) hash ^= Due.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Batch != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Batch);
      }
      if (Bind != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Bind);
      }
      if (Weight != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Weight);
      }
      if (Job != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(Job);
      }
      if (object_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Object);
      }
      if (Due != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Due);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Batch != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Batch);
      }
      if (Bind != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Bind);
      }
      if (Weight != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Weight);
      }
      if (Job != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(Job);
      }
      if (object_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Object);
      }
      if (Due != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Due);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Batch != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Batch);
      }
      if (Bind != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Bind);
      }
      if (Weight != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Weight);
      }
      if (Job != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Job);
      }
      if (object_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Object);
      }
      if (Due != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Due);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Award other) {
      if (other == null) {
        return;
      }
      if (other.Batch != 0L) {
        Batch = other.Batch;
      }
      if (other.Bind != 0L) {
        Bind = other.Bind;
      }
      if (other.Weight != 0L) {
        Weight = other.Weight;
      }
      if (other.Job != 0L) {
        Job = other.Job;
      }
      if (other.object_ != null) {
        if (object_ == null) {
          Object = new global::Pb.Object();
        }
        Object.MergeFrom(other.Object);
      }
      if (other.Due != 0L) {
        Due = other.Due;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Batch = input.ReadSInt64();
            break;
          }
          case 16: {
            Bind = input.ReadSInt64();
            break;
          }
          case 24: {
            Weight = input.ReadSInt64();
            break;
          }
          case 32: {
            Job = input.ReadSInt64();
            break;
          }
          case 42: {
            if (object_ == null) {
              Object = new global::Pb.Object();
            }
            input.ReadMessage(Object);
            break;
          }
          case 48: {
            Due = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Batch = input.ReadSInt64();
            break;
          }
          case 16: {
            Bind = input.ReadSInt64();
            break;
          }
          case 24: {
            Weight = input.ReadSInt64();
            break;
          }
          case 32: {
            Job = input.ReadSInt64();
            break;
          }
          case 42: {
            if (object_ == null) {
              Object = new global::Pb.Object();
            }
            input.ReadMessage(Object);
            break;
          }
          case 48: {
            Due = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Item : pb::IMessage<Item>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Item> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Item() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Item(Item other) : this() {
      idx_ = other.idx_;
      id_ = other.id_;
      cid_ = other.cid_;
      count_ = other.count_;
      bind_ = other.bind_;
      due_ = other.due_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Item Clone() {
      return new Item(this);
    }

    /// <summary>Field number for the "idx" field.</summary>
    public const int IdxFieldNumber = 1;
    private long idx_;
    /// <summary>
    /// 编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Idx {
      get { return idx_; }
      set {
        idx_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    /// <summary>
    /// 唯一id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 3;
    private long cid_;
    /// <summary>
    /// 配置id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 4;
    private long count_;
    /// <summary>
    /// 数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "bind" field.</summary>
    public const int BindFieldNumber = 5;
    private long bind_;
    /// <summary>
    /// 是否绑定 0-非绑定，1-绑定
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Bind {
      get { return bind_; }
      set {
        bind_ = value;
      }
    }

    /// <summary>Field number for the "due" field.</summary>
    public const int DueFieldNumber = 6;
    private long due_;
    /// <summary>
    /// 有效时间 0 为无限期
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Due {
      get { return due_; }
      set {
        due_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Item other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Idx != other.Idx) return false;
      if (Id != other.Id) return false;
      if (Cid != other.Cid) return false;
      if (Count != other.Count) return false;
      if (Bind != other.Bind) return false;
      if (Due != other.Due) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Idx != 0L) hash ^= Idx.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Cid != 0L) hash ^= Cid.GetHashCode();
      if (Count != 0L) hash ^= Count.GetHashCode();
      if (Bind != 0L) hash ^= Bind.GetHashCode();
      if (Due != 0L) hash ^= Due.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Idx);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Id);
      }
      if (Cid != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Cid);
      }
      if (Count != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(Count);
      }
      if (Bind != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(Bind);
      }
      if (Due != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Due);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Idx != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Idx);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Id);
      }
      if (Cid != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Cid);
      }
      if (Count != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(Count);
      }
      if (Bind != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(Bind);
      }
      if (Due != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(Due);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Idx != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Idx);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Id);
      }
      if (Cid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Cid);
      }
      if (Count != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Count);
      }
      if (Bind != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Bind);
      }
      if (Due != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Due);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Item other) {
      if (other == null) {
        return;
      }
      if (other.Idx != 0L) {
        Idx = other.Idx;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Cid != 0L) {
        Cid = other.Cid;
      }
      if (other.Count != 0L) {
        Count = other.Count;
      }
      if (other.Bind != 0L) {
        Bind = other.Bind;
      }
      if (other.Due != 0L) {
        Due = other.Due;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Idx = input.ReadSInt64();
            break;
          }
          case 16: {
            Id = input.ReadSInt64();
            break;
          }
          case 24: {
            Cid = input.ReadSInt64();
            break;
          }
          case 32: {
            Count = input.ReadSInt64();
            break;
          }
          case 40: {
            Bind = input.ReadSInt64();
            break;
          }
          case 48: {
            Due = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Idx = input.ReadSInt64();
            break;
          }
          case 16: {
            Id = input.ReadSInt64();
            break;
          }
          case 24: {
            Cid = input.ReadSInt64();
            break;
          }
          case 32: {
            Count = input.ReadSInt64();
            break;
          }
          case 40: {
            Bind = input.ReadSInt64();
            break;
          }
          case 48: {
            Due = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Time : pb::IMessage<Time>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Time> _parser = new pb::MessageParser<Time>(() => new Time());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Time> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Time() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Time(Time other) : this() {
      dsec_ = other.dsec_;
      wsec_ = other.wsec_;
      wday_ = other.wday_;
      sec_ = other.sec_;
      young_ = other.young_;
      loginTime_ = other.loginTime_;
      openDay_ = other.openDay_;
      mergeDay_ = other.mergeDay_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Time Clone() {
      return new Time(this);
    }

    /// <summary>Field number for the "dsec" field.</summary>
    public const int DsecFieldNumber = 1;
    private long dsec_;
    /// <summary>
    /// 今日在线时间 秒
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Dsec {
      get { return dsec_; }
      set {
        dsec_ = value;
      }
    }

    /// <summary>Field number for the "wsec" field.</summary>
    public const int WsecFieldNumber = 2;
    private long wsec_;
    /// <summary>
    /// 本周在线时间 秒
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Wsec {
      get { return wsec_; }
      set {
        wsec_ = value;
      }
    }

    /// <summary>Field number for the "wday" field.</summary>
    public const int WdayFieldNumber = 3;
    private long wday_;
    /// <summary>
    /// 本周在线天数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Wday {
      get { return wday_; }
      set {
        wday_ = value;
      }
    }

    /// <summary>Field number for the "sec" field.</summary>
    public const int SecFieldNumber = 4;
    private long sec_;
    /// <summary>
    /// 总在线时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sec {
      get { return sec_; }
      set {
        sec_ = value;
      }
    }

    /// <summary>Field number for the "young" field.</summary>
    public const int YoungFieldNumber = 5;
    private long young_;
    /// <summary>
    /// 防沉迷时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Young {
      get { return young_; }
      set {
        young_ = value;
      }
    }

    /// <summary>Field number for the "login_time" field.</summary>
    public const int LoginTimeFieldNumber = 6;
    private long loginTime_;
    /// <summary>
    /// 本次登录时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LoginTime {
      get { return loginTime_; }
      set {
        loginTime_ = value;
      }
    }

    /// <summary>Field number for the "open_day" field.</summary>
    public const int OpenDayFieldNumber = 7;
    private long openDay_;
    /// <summary>
    /// 服务器开服天数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OpenDay {
      get { return openDay_; }
      set {
        openDay_ = value;
      }
    }

    /// <summary>Field number for the "merge_day" field.</summary>
    public const int MergeDayFieldNumber = 8;
    private long mergeDay_;
    /// <summary>
    /// 服务器合服天数，未合服为0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MergeDay {
      get { return mergeDay_; }
      set {
        mergeDay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Time);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Time other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Dsec != other.Dsec) return false;
      if (Wsec != other.Wsec) return false;
      if (Wday != other.Wday) return false;
      if (Sec != other.Sec) return false;
      if (Young != other.Young) return false;
      if (LoginTime != other.LoginTime) return false;
      if (OpenDay != other.OpenDay) return false;
      if (MergeDay != other.MergeDay) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Dsec != 0L) hash ^= Dsec.GetHashCode();
      if (Wsec != 0L) hash ^= Wsec.GetHashCode();
      if (Wday != 0L) hash ^= Wday.GetHashCode();
      if (Sec != 0L) hash ^= Sec.GetHashCode();
      if (Young != 0L) hash ^= Young.GetHashCode();
      if (LoginTime != 0L) hash ^= LoginTime.GetHashCode();
      if (OpenDay != 0L) hash ^= OpenDay.GetHashCode();
      if (MergeDay != 0L) hash ^= MergeDay.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Dsec != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Dsec);
      }
      if (Wsec != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Wsec);
      }
      if (Wday != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Wday);
      }
      if (Sec != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(Sec);
      }
      if (Young != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(Young);
      }
      if (LoginTime != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(LoginTime);
      }
      if (OpenDay != 0L) {
        output.WriteRawTag(56);
        output.WriteSInt64(OpenDay);
      }
      if (MergeDay != 0L) {
        output.WriteRawTag(64);
        output.WriteSInt64(MergeDay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Dsec != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Dsec);
      }
      if (Wsec != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Wsec);
      }
      if (Wday != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Wday);
      }
      if (Sec != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(Sec);
      }
      if (Young != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(Young);
      }
      if (LoginTime != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(LoginTime);
      }
      if (OpenDay != 0L) {
        output.WriteRawTag(56);
        output.WriteSInt64(OpenDay);
      }
      if (MergeDay != 0L) {
        output.WriteRawTag(64);
        output.WriteSInt64(MergeDay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Dsec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Dsec);
      }
      if (Wsec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Wsec);
      }
      if (Wday != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Wday);
      }
      if (Sec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Sec);
      }
      if (Young != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Young);
      }
      if (LoginTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(LoginTime);
      }
      if (OpenDay != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(OpenDay);
      }
      if (MergeDay != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(MergeDay);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Time other) {
      if (other == null) {
        return;
      }
      if (other.Dsec != 0L) {
        Dsec = other.Dsec;
      }
      if (other.Wsec != 0L) {
        Wsec = other.Wsec;
      }
      if (other.Wday != 0L) {
        Wday = other.Wday;
      }
      if (other.Sec != 0L) {
        Sec = other.Sec;
      }
      if (other.Young != 0L) {
        Young = other.Young;
      }
      if (other.LoginTime != 0L) {
        LoginTime = other.LoginTime;
      }
      if (other.OpenDay != 0L) {
        OpenDay = other.OpenDay;
      }
      if (other.MergeDay != 0L) {
        MergeDay = other.MergeDay;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Dsec = input.ReadSInt64();
            break;
          }
          case 16: {
            Wsec = input.ReadSInt64();
            break;
          }
          case 24: {
            Wday = input.ReadSInt64();
            break;
          }
          case 32: {
            Sec = input.ReadSInt64();
            break;
          }
          case 40: {
            Young = input.ReadSInt64();
            break;
          }
          case 48: {
            LoginTime = input.ReadSInt64();
            break;
          }
          case 56: {
            OpenDay = input.ReadSInt64();
            break;
          }
          case 64: {
            MergeDay = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Dsec = input.ReadSInt64();
            break;
          }
          case 16: {
            Wsec = input.ReadSInt64();
            break;
          }
          case 24: {
            Wday = input.ReadSInt64();
            break;
          }
          case 32: {
            Sec = input.ReadSInt64();
            break;
          }
          case 40: {
            Young = input.ReadSInt64();
            break;
          }
          case 48: {
            LoginTime = input.ReadSInt64();
            break;
          }
          case 56: {
            OpenDay = input.ReadSInt64();
            break;
          }
          case 64: {
            MergeDay = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Attr : pb::IMessage<Attr>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Attr> _parser = new pb::MessageParser<Attr>(() => new Attr());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Attr> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Attr() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Attr(Attr other) : this() {
      ty_ = other.ty_;
      val_ = other.val_;
      rate_ = other.rate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Attr Clone() {
      return new Attr(this);
    }

    /// <summary>Field number for the "ty" field.</summary>
    public const int TyFieldNumber = 1;
    private global::Pb.EAttrType.Types.T ty_ = global::Pb.EAttrType.Types.T.Invalid;
    /// <summary>
    /// 类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.EAttrType.Types.T Ty {
      get { return ty_; }
      set {
        ty_ = value;
      }
    }

    /// <summary>Field number for the "val" field.</summary>
    public const int ValFieldNumber = 2;
    private long val_;
    /// <summary>
    /// 值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Val {
      get { return val_; }
      set {
        val_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 3;
    private long rate_;
    /// <summary>
    /// 比率
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Attr);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Attr other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ty != other.Ty) return false;
      if (Val != other.Val) return false;
      if (Rate != other.Rate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ty != global::Pb.EAttrType.Types.T.Invalid) hash ^= Ty.GetHashCode();
      if (Val != 0L) hash ^= Val.GetHashCode();
      if (Rate != 0L) hash ^= Rate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ty != global::Pb.EAttrType.Types.T.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Ty);
      }
      if (Val != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Val);
      }
      if (Rate != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ty != global::Pb.EAttrType.Types.T.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Ty);
      }
      if (Val != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Val);
      }
      if (Rate != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ty != global::Pb.EAttrType.Types.T.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Ty);
      }
      if (Val != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Val);
      }
      if (Rate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Rate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Attr other) {
      if (other == null) {
        return;
      }
      if (other.Ty != global::Pb.EAttrType.Types.T.Invalid) {
        Ty = other.Ty;
      }
      if (other.Val != 0L) {
        Val = other.Val;
      }
      if (other.Rate != 0L) {
        Rate = other.Rate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Ty = (global::Pb.EAttrType.Types.T) input.ReadEnum();
            break;
          }
          case 16: {
            Val = input.ReadSInt64();
            break;
          }
          case 24: {
            Rate = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Ty = (global::Pb.EAttrType.Types.T) input.ReadEnum();
            break;
          }
          case 16: {
            Val = input.ReadSInt64();
            break;
          }
          case 24: {
            Rate = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Vector : pb::IMessage<Vector>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Vector> _parser = new pb::MessageParser<Vector>(() => new Vector());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Vector> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DataReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vector() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vector(Vector other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vector Clone() {
      return new Vector(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private long x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private long y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private long z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Vector);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Vector other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (Z != other.Z) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0L) hash ^= X.GetHashCode();
      if (Y != 0L) hash ^= Y.GetHashCode();
      if (Z != 0L) hash ^= Z.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(X);
      }
      if (Y != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Y);
      }
      if (Z != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(X);
      }
      if (Y != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Y);
      }
      if (Z != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(X);
      }
      if (Y != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Y);
      }
      if (Z != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Z);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Vector other) {
      if (other == null) {
        return;
      }
      if (other.X != 0L) {
        X = other.X;
      }
      if (other.Y != 0L) {
        Y = other.Y;
      }
      if (other.Z != 0L) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            X = input.ReadSInt64();
            break;
          }
          case 16: {
            Y = input.ReadSInt64();
            break;
          }
          case 24: {
            Z = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            X = input.ReadSInt64();
            break;
          }
          case 16: {
            Y = input.ReadSInt64();
            break;
          }
          case 24: {
            Z = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
