// Code generated by pbgen. DO NOT EDIT.
// source: cmd.proto, cmd_req.proto, cmd_rsp.proto, cmd_dsp.proto

package pb

import (
	"genpb/pb"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

var _parser = NewParser()

func init() {
	_parser.Load()
}

func Unmarshal(key EKey_T, data []byte) proto.Message {
	return _parser.Unmarshal(key, data)
}

// parser handles protobuf message parsing by EKey
type parser struct {
	types map[EKey_T]protoreflect.Type
}

// NewParser creates a new Parser instance
func NewParser() *parser {
	return &parser{
		types: make(map[EKey_T]protoreflect.Type),
	}
}

// Register registers a message type for a given EKey
func (p *parser) Register(key EKey_T, msg proto.Message) {
	p.types[key] = msg.ProtoReflect().Type()
}

// GetType returns the message type for the given EKey
func (p *parser) GetType(key EKey_T) (protoreflect.Type, bool) {
	typ, ok := p.types[key]
	return typ, ok
}

// New creates a new message instance for the given EKey
func (p *parser) New(key EKey_T) proto.Message {
	typ, ok := p.GetType(key)
	if !ok {
		return nil
	}
	return proto.New(typ).Interface()
}

// Unmarshal unmarshals binary data into a new message instance
func (p *parser) Unmarshal(key EKey_T, data []byte) proto.Message {
	msg := p.New(key)
	if msg == nil {
		return nil
	}
	if err := proto.Unmarshal(data, msg); err != nil {
		return nil
	}
	return msg
}

// Load registers all message types
func (p *parser) Load() {
	p.Register(EKey_Login, &ReqLogin{})
	p.Register(EKey_CreateRole, &ReqCreateRole{})
	p.Register(EKey_DeleteRole, &ReqDeleteRole{})
	p.Register(EKey_LoginRole, &ReqLoginRole{})
	p.Register(EKey_Ping, &ReqPing{})
	p.Register(EKey_PingXXX, &ReqPingXXX{})
	p.Register(EKey_EnterScene, &ReqEnterScene{})
	p.Register(EKey_TestEnter, &ReqTestEnter{})
	p.Register(EKey_Login, &RspLogin{})
	p.Register(EKey_CreateRole, &RspCreateRole{})
	p.Register(EKey_DeleteRole, &RspDeleteRole{})
	p.Register(EKey_LoginRole, &RspLoginRole{})
	p.Register(EKey_Ping, &RspPing{})
	p.Register(EKey_PingXXX, &RspPingXXX{})
	p.Register(EKey_EnterScene, &RspEnterScene{})
	p.Register(EKey_TestEnter, &RspTestEnter{})
	p.Register(EKey_SyncLoginFast, &RspSyncLoginFast{})
	p.Register(EKey_SyncLoginData, &RspSyncLoginData{})
	p.Register(EKey_SyncServerMaintain, &RspSyncServerMaintain{})
	p.Register(EKey_SyncKickRole, &RspSyncKickRole{})
	p.Register(EKey_SyncPreparedEnterScene, &RspSyncPreparedEnterScene{})
	p.Register(EKey_SyncTest, &RspSyncTest{})
}

func (msg *ReqLogin) Key() pb.EKey {
	return pb.EKey_Login
}

func (msg *ReqCreateRole) Key() pb.EKey {
	return pb.EKey_CreateRole
}

func (msg *ReqDeleteRole) Key() pb.EKey {
	return pb.EKey_DeleteRole
}

func (msg *ReqLoginRole) Key() pb.EKey {
	return pb.EKey_LoginRole
}

func (msg *ReqPing) Key() pb.EKey {
	return pb.EKey_Ping
}

func (msg *ReqPingXXX) Key() pb.EKey {
	return pb.EKey_PingXXX
}

func (msg *ReqEnterScene) Key() pb.EKey {
	return pb.EKey_EnterScene
}

func (msg *ReqTestEnter) Key() pb.EKey {
	return pb.EKey_TestEnter
}

func (msg *RspLogin) Key() pb.EKey {
	return pb.EKey_Login
}

func (msg *RspCreateRole) Key() pb.EKey {
	return pb.EKey_CreateRole
}

func (msg *RspDeleteRole) Key() pb.EKey {
	return pb.EKey_DeleteRole
}

func (msg *RspLoginRole) Key() pb.EKey {
	return pb.EKey_LoginRole
}

func (msg *RspPing) Key() pb.EKey {
	return pb.EKey_Ping
}

func (msg *RspPingXXX) Key() pb.EKey {
	return pb.EKey_PingXXX
}

func (msg *RspEnterScene) Key() pb.EKey {
	return pb.EKey_EnterScene
}

func (msg *RspTestEnter) Key() pb.EKey {
	return pb.EKey_TestEnter
}

func (msg *RspSyncLoginFast) Key() pb.EKey {
	return pb.EKey_SyncLoginFast
}

func (msg *RspSyncLoginData) Key() pb.EKey {
	return pb.EKey_SyncLoginData
}

func (msg *RspSyncServerMaintain) Key() pb.EKey {
	return pb.EKey_SyncServerMaintain
}

func (msg *RspSyncKickRole) Key() pb.EKey {
	return pb.EKey_SyncKickRole
}

func (msg *RspSyncPreparedEnterScene) Key() pb.EKey {
	return pb.EKey_SyncPreparedEnterScene
}

func (msg *RspSyncTest) Key() pb.EKey {
	return pb.EKey_SyncTest
}

