// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd_dsp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 同步快速重登 token
type RspSyncLoginFast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            ESignInFastType_T      `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.ESignInFastType_T" json:"ty,omitempty"` // 可快速重登的类型
	Timestamp     int64                  `protobuf:"zigzag64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // 时间戳
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                      // token
	Magic         int64                  `protobuf:"zigzag64,4,opt,name=magic,proto3" json:"magic,omitempty"`                   // 魔数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspSyncLoginFast) Reset() {
	*x = RspSyncLoginFast{}
	mi := &file_cmd_dsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspSyncLoginFast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSyncLoginFast) ProtoMessage() {}

func (x *RspSyncLoginFast) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSyncLoginFast.ProtoReflect.Descriptor instead.
func (*RspSyncLoginFast) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{0}
}

func (x *RspSyncLoginFast) GetTy() ESignInFastType_T {
	if x != nil {
		return x.Ty
	}
	return ESignInFastType_Invalid
}

func (x *RspSyncLoginFast) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RspSyncLoginFast) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RspSyncLoginFast) GetMagic() int64 {
	if x != nil {
		return x.Magic
	}
	return 0
}

type RspSyncLoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SLoginData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 登录必要数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspSyncLoginData) Reset() {
	*x = RspSyncLoginData{}
	mi := &file_cmd_dsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspSyncLoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSyncLoginData) ProtoMessage() {}

func (x *RspSyncLoginData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSyncLoginData.ProtoReflect.Descriptor instead.
func (*RspSyncLoginData) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{1}
}

func (x *RspSyncLoginData) GetData() *SLoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务器维护
type RspSyncServerMaintain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RebootTime    int64                  `protobuf:"zigzag64,1,opt,name=reboot_time,json=rebootTime,proto3" json:"reboot_time,omitempty"`       // 预计开服时间戳，为 0 代表未知
	ShutdownTime  int64                  `protobuf:"zigzag64,2,opt,name=shutdown_time,json=shutdownTime,proto3" json:"shutdown_time,omitempty"` // 关服时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspSyncServerMaintain) Reset() {
	*x = RspSyncServerMaintain{}
	mi := &file_cmd_dsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspSyncServerMaintain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSyncServerMaintain) ProtoMessage() {}

func (x *RspSyncServerMaintain) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSyncServerMaintain.ProtoReflect.Descriptor instead.
func (*RspSyncServerMaintain) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{2}
}

func (x *RspSyncServerMaintain) GetRebootTime() int64 {
	if x != nil {
		return x.RebootTime
	}
	return 0
}

func (x *RspSyncServerMaintain) GetShutdownTime() int64 {
	if x != nil {
		return x.ShutdownTime
	}
	return 0
}

// 踢玩家下线
type RspSyncKickRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            EKickType_T            `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.EKickType_T" json:"ty,omitempty"`     // 踢下线类型
	SessId        int64                  `protobuf:"zigzag64,2,opt,name=sess_id,json=sessId,proto3" json:"sess_id,omitempty"` // sess id，服务器使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspSyncKickRole) Reset() {
	*x = RspSyncKickRole{}
	mi := &file_cmd_dsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspSyncKickRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSyncKickRole) ProtoMessage() {}

func (x *RspSyncKickRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSyncKickRole.ProtoReflect.Descriptor instead.
func (*RspSyncKickRole) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{3}
}

func (x *RspSyncKickRole) GetTy() EKickType_T {
	if x != nil {
		return x.Ty
	}
	return EKickType_Invalid
}

func (x *RspSyncKickRole) GetSessId() int64 {
	if x != nil {
		return x.SessId
	}
	return 0
}

// 更新邮件
type RspSyncPreparedEnterScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspSyncPreparedEnterScene) Reset() {
	*x = RspSyncPreparedEnterScene{}
	mi := &file_cmd_dsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspSyncPreparedEnterScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSyncPreparedEnterScene) ProtoMessage() {}

func (x *RspSyncPreparedEnterScene) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSyncPreparedEnterScene.ProtoReflect.Descriptor instead.
func (*RspSyncPreparedEnterScene) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{4}
}

type RspSyncTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspSyncTest) Reset() {
	*x = RspSyncTest{}
	mi := &file_cmd_dsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspSyncTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSyncTest) ProtoMessage() {}

func (x *RspSyncTest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSyncTest.ProtoReflect.Descriptor instead.
func (*RspSyncTest) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{5}
}

var File_cmd_dsp_proto protoreflect.FileDescriptor

const file_cmd_dsp_proto_rawDesc = "" +
	"\n" +
	"\rcmd_dsp.proto\x12\x02pb\x1a\n" +
	"data.proto\x1a\n" +
	"enum.proto\"\x83\x01\n" +
	"\x10RspSyncLoginFast\x12%\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x15.pb.ESignInFastType.TR\x02ty\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x12R\ttimestamp\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x14\n" +
	"\x05magic\x18\x04 \x01(\x12R\x05magic\"6\n" +
	"\x10RspSyncLoginData\x12\"\n" +
	"\x04data\x18\x01 \x01(\v2\x0e.pb.SLoginDataR\x04data\"]\n" +
	"\x15RspSyncServerMaintain\x12\x1f\n" +
	"\vreboot_time\x18\x01 \x01(\x12R\n" +
	"rebootTime\x12#\n" +
	"\rshutdown_time\x18\x02 \x01(\x12R\fshutdownTime\"K\n" +
	"\x0fRspSyncKickRole\x12\x1f\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x0f.pb.EKickType.TR\x02ty\x12\x17\n" +
	"\asess_id\x18\x02 \x01(\x12R\x06sessId\"\x1b\n" +
	"\x19RspSyncPreparedEnterScene\"\r\n" +
	"\vRspSyncTestB\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_dsp_proto_rawDescOnce sync.Once
	file_cmd_dsp_proto_rawDescData []byte
)

func file_cmd_dsp_proto_rawDescGZIP() []byte {
	file_cmd_dsp_proto_rawDescOnce.Do(func() {
		file_cmd_dsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_dsp_proto_rawDesc), len(file_cmd_dsp_proto_rawDesc)))
	})
	return file_cmd_dsp_proto_rawDescData
}

var file_cmd_dsp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cmd_dsp_proto_goTypes = []any{
	(*RspSyncLoginFast)(nil),          // 0: pb.RspSyncLoginFast
	(*RspSyncLoginData)(nil),          // 1: pb.RspSyncLoginData
	(*RspSyncServerMaintain)(nil),     // 2: pb.RspSyncServerMaintain
	(*RspSyncKickRole)(nil),           // 3: pb.RspSyncKickRole
	(*RspSyncPreparedEnterScene)(nil), // 4: pb.RspSyncPreparedEnterScene
	(*RspSyncTest)(nil),               // 5: pb.RspSyncTest
	(ESignInFastType_T)(0),            // 6: pb.ESignInFastType.T
	(*SLoginData)(nil),                // 7: pb.SLoginData
	(EKickType_T)(0),                  // 8: pb.EKickType.T
}
var file_cmd_dsp_proto_depIdxs = []int32{
	6, // 0: pb.RspSyncLoginFast.ty:type_name -> pb.ESignInFastType.T
	7, // 1: pb.RspSyncLoginData.data:type_name -> pb.SLoginData
	8, // 2: pb.RspSyncKickRole.ty:type_name -> pb.EKickType.T
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cmd_dsp_proto_init() }
func file_cmd_dsp_proto_init() {
	if File_cmd_dsp_proto != nil {
		return
	}
	file_data_proto_init()
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_dsp_proto_rawDesc), len(file_cmd_dsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_dsp_proto_goTypes,
		DependencyIndexes: file_cmd_dsp_proto_depIdxs,
		MessageInfos:      file_cmd_dsp_proto_msgTypes,
	}.Build()
	File_cmd_dsp_proto = out.File
	file_cmd_dsp_proto_goTypes = nil
	file_cmd_dsp_proto_depIdxs = nil
}
